"""empty message

Revision ID: 43b357fdf900
Revises: 84282334f56c
Create Date: 2021-10-22 14:41:38.892300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b357fdf900'
down_revision = '84282334f56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('offers', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('offers', 'latlon')
    op.add_column('requests', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('requests', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('requests', 'latlon')
    op.add_column('users', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('users', 'latlon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latlon', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'lon')
    op.drop_column('users', 'lat')
    op.add_column('requests', sa.Column('latlon', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('requests', 'lon')
    op.drop_column('requests', 'lat')
    op.add_column('offers', sa.Column('latlon', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('offers', 'lon')
    op.drop_column('offers', 'lat')
    # ### end Alembic commands ###
