"""empty message

Revision ID: a5a0af7a9c17
Revises: 43b357fdf900
Create Date: 2021-10-22 17:15:13.437126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5a0af7a9c17'
down_revision = '43b357fdf900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'city')
    op.drop_column('offers', 'lon')
    op.drop_column('offers', 'lat')
    op.drop_column('offers', 'location_range')
    op.drop_column('offers', 'state')
    op.drop_column('offers', 'zipcode')
    op.drop_column('requests', 'city')
    op.drop_column('requests', 'lon')
    op.drop_column('requests', 'lat')
    op.drop_column('requests', 'location_range')
    op.drop_column('requests', 'state')
    op.drop_column('requests', 'zipcode')
    op.add_column('users', sa.Column('range', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=False))
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'zipcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zipcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_column('users', 'address')
    op.drop_column('users', 'range')
    op.add_column('requests', sa.Column('zipcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('location_range', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('zipcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('location_range', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
