"""empty message

Revision ID: 860f35a967aa
Revises: ffdc0a98111c
Create Date: 2021-10-24 15:49:54.515059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860f35a967aa'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('public_email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('range', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('lon', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'time_updated')
    op.drop_column('users', 'time_created')
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'lon')
    op.drop_column('users', 'lat')
    op.drop_column('users', 'address')
    op.drop_column('users', 'range')
    op.drop_column('users', 'public_email')
    op.drop_table('reviews')
    op.drop_table('requests')
    op.drop_table('offers')
    # ### end Alembic commands ###
