"""empty message

Revision ID: c299cde3fda4
Revises: ffdc0a98111c
Create Date: 2021-10-19 11:29:06.675039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c299cde3fda4'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('private_email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('public_email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('latitude', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('longitude', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['public_email'])
    op.create_unique_constraint(None, 'users', ['private_email'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'time_updated')
    op.drop_column('users', 'time_created')
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'public_email')
    op.drop_column('users', 'private_email')
    # ### end Alembic commands ###
