"""empty message

Revision ID: ddea0e48b213
Revises: 433af318feb8
Create Date: 2021-10-20 17:04:36.969813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddea0e48b213'
down_revision = '433af318feb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('zipcode', sa.String(length=10), nullable=False))
    op.drop_column('offers', 'latitude')
    op.drop_column('offers', 'longitude')
    op.add_column('requests', sa.Column('zipcode', sa.String(length=10), nullable=False))
    op.drop_column('requests', 'latitude')
    op.drop_column('requests', 'longitude')
    op.add_column('users', sa.Column('zipcode', sa.String(length=10), nullable=False))
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('users', 'zipcode')
    op.add_column('requests', sa.Column('longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('requests', 'zipcode')
    op.add_column('offers', sa.Column('longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('offers', 'zipcode')
    # ### end Alembic commands ###
