"""empty message

Revision ID: 433af318feb8
Revises: cfdd639f3697
Create Date: 2021-10-20 10:26:28.130289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433af318feb8'
down_revision = 'cfdd639f3697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.drop_constraint('users_private_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'private_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('private_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_private_email_key', 'users', ['private_email'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
