"""empty message

Revision ID: 84282334f56c
Revises: ddea0e48b213
Create Date: 2021-10-22 11:00:16.941653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84282334f56c'
down_revision = 'ddea0e48b213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('offers', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('offers', sa.Column('latlon', sa.String(length=255), nullable=False))
    op.add_column('requests', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('requests', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('requests', sa.Column('latlon', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('users', sa.Column('latlon', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'latlon')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('requests', 'latlon')
    op.drop_column('requests', 'state')
    op.drop_column('requests', 'city')
    op.drop_column('offers', 'latlon')
    op.drop_column('offers', 'state')
    op.drop_column('offers', 'city')
    # ### end Alembic commands ###
